### ISSUE TITLE
授業log 20200218 新谷スクール

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#119]
授業担当：中西
授業目的：多角的な視点を持つ
授業目標：異文化、差別に対する自分の意見を持つ
参照：#17
参加生徒：伊村道瑠, 宇野珠央, 新谷珠央, ななぎ, 新井理子, 松岡和佳

**Comment by NakanishiHiroki** [comment]
# 授業の流れ
- アンケート
- 記事読む
- 単語解説
- 議論

# 導入アンケート
![コロナウイルス差別問題導入アンケート_page-0001](https://user-images.githubusercontent.com/49800056/74720933-eb466100-5279-11ea-8ab0-b726f592dd8f.jpg)

**Comment by NakanishiHiroki** [comment]
# 振り返り
## 中西
読むのに時間がかかって議論の時間が少なかった。
内容の理解も中学組は厳しそうだった。
漢字の解説などはみんな熱心に聞く
## 中西
読むのに時間がかかって議論の時間が少なかった。
内容の理解も中学組は厳しそうだった。
漢字の解説などはみんな熱心に聞くので学校の授業形式になれているのだろう。
