### ISSUE TITLE
授業log 20200225 新谷スクール

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/contents#146]
授業担当：亀井
授業目的：思考の体力をつける
授業目標：
参照：#163
参加生徒：橋本ななぎ, 伊村道瑠, 宇野珠央, 植村彩葉, こうじ, けんと
生徒管理シート：https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA

**Comment by NakanishiHiroki** [comment]
# 授業の流れ
- ルール説明
-- 実際にプレイ

**Comment by NakanishiHiroki** [comment]
# 今週の一問
#164

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
みんな手を上げたがらないな
テストプレイの相手がすぐに決まらなかった

チーム分けのときにコミュニケーションをとれる人ととれない人がいる
こうじ、けんとは誰と組んでも喋れるが、みちる、たまおは絶対につるんで他とあまり喋らない
ななぎは同学年がおらず、話し辛そうにしてた

ゲーム自体はいいプレイも多くて見ていて楽しかった
Quartoはラテン語で4を意味するらしい
Quoridorは廊下という意味の英語corridorから来てるらしい

テスト前なのでテスト勉強したいという空気があったのでゲームが長引くと集中が切れてきた

自習の時間はほとんど、ななぎに正負の数についての授業をしていた
のみこみと計算が早いので、簡単なところはすっとばして、複雑な計算をやらせてみた
