### ISSUE TITLE
授業log 20200303 新谷スクール

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/contents#159]
授業担当：亀井, 中西
授業目的：文章読解力をつける
授業目標：文章を読んで要旨を理解する
参照：#173

参加生徒：伊村道瑠, 宇野珠央, 新井理子, 新谷珠央, 矢里たくと, 橋本ななぎ, ゆきと, りょうせい

[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)

**Comment by kameiatsushi** [comment]
# 導入
国語力が非常に重要である
文章を正しく読み取ることができたなら、あとは1人で勉強を進めることができる

読解力をつける最善の手段は文章を読むことである
文章を読んで、それの内容についてあれこれ考えることで、根幹となる思考力を養うことができる

**Comment by kameiatsushi** [comment]
# 今週の一問

**Comment by kameiatsushi** [comment]
# 振り返り
中西

**Comment by kameiatsushi** [comment]
# 振り返り
亀井

**Comment by NakanishiHiroki** [comment]
# 振り返り　中西
分からないところ線引かして引いていない人に当てるのは良さそう。
レスポンスはあまりないが。小6組は結構賢いのでレベル高めの文章でも読めるかも。
小6はの意欲は感じるのでそこを主導で議論とかできると良い。
