### ISSUE TITLE
授業log 20200310 新谷スクール

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#179]
授業担当：亀井, 中西
授業目的：知識があることの楽しさを味わう
授業目標：口に二本足して漢字作るクイズで一人15文字は出す
参照：#192

参加生徒：伊村道瑠, 宇野珠央, 橋本ななぎ, 松岡和佳
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)

**Comment by NakanishiHiroki** [comment]
# 授業内容

**Comment by NakanishiHiroki** [comment]
# 今週の一問
#188

**Comment by NakanishiHiroki** [comment]
# 準備物
- 今週の一問10枚
- 漢字熟語しりとり問題(裏はMEMOとして使用)

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
