### ISSUE TITLE
授業log 20200211 新谷スクール スクエアイット

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#22]
授業担当：
授業目的：
授業目標：
参照：#31
参加生徒：あじちりょう、青山ゆきと、大滝りょうせい、矢里たくと、橋本ななぎ、青山しょうたろう、植村あやは、新谷心苗

**Comment by kameiatsushi** [comment]
＃ボードゲームをするメリット
## そもそも勉強ってなんのためにするのか
数学とかは社会に出てから使うことない
しかし、その思考の過程は重要である

香川県でゲーム禁止令が出たが、1時間程度のゲームでは何の役にもたたない

**Comment by kameiatsushi** [comment]
# スクエアイットをプレイする
## デモンストレーション
ルール説明をして、実際に代表者2人にプレイしてもらう
やってみた感じ、何が重要そうかを考える

## トーナメント
トーナメント表を作る
それに従って試合をしていく

## 作戦

**Comment by NakanishiHiroki** [comment]
# 今週の一問
#33

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
```
超盛り上がった
小学生扱いやすい
```
