### ISSUE TITLE
イベントlog 2020/04/17 雑学雑談 ~ITの話~

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#294]
担当：亀井, 中西
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)
[授業フォーマット](https://github.com/life-lab-kyoto/contents/wiki/%E6%8E%88%E6%A5%AD%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)

meeting url：https://us02web.zoom.us/j/88111515634?pwd=YXZCWmRhaHJoUnZieWlvVTU0eFBZQT09
Meeting ID: 881 1151 5634
Password: 020619

参加生徒：内藤結友, 本庄柾統（母）, 大滝羚惺, 青山侑己人, 中村健人, 中村康二, 佐久間優成, 三上はるや, 田内彩, Shubham, 橋本和煌, 矢里拓東, こみなとさん, こまたさん, 西尾詩

**Comment by kameiatsushi** [comment]
# 流れ
### 事前準備
1. 事前にテーマに沿ったことを調べて、まとめたものを提出してもらう
1. 付随して出て来た疑問も提出してもらう
1. それをもとに話す内容を考える

### 当日
1. 調べてきたことを発表
1. 提出された疑問に答えていく
1. そこから派生して雑談する
1. 最後今日得た知識を発表してもらう

**Comment by kameiatsushi** [comment]
# 話す内容
- googleのサーバにある情報量
- 1GBとかのギガってなに？
- 0と1だけでどうやって情報を伝えるの？

**Comment by NakanishiHiroki** [comment]
”オンライン雑学雑談 ~ITの話”にお申込みいただきありがとうございます。
本日4月17日の19時にzoomで下のルームにご参加ください。

meeting url：https://us02web.zoom.us/j/88111515634?pwd=YXZCWmRhaHJoUnZieWlvVTU0eFBZQT09
Meeting ID: 881 1151 5634
Password: 020619

※出来るだけ本名で名前を登録してくださるとありがたいです！

質問や知りたいことを送っていない方は送ってください！
※全ての質問に答えられるかは分かりませんのでご了承ください。

**Comment by NakanishiHiroki** [comment]
# 案内送信済み
## 中西から
大滝羚惺, 青山侑己人,橋本和煌, 矢里拓東,三上はるや,佐久間優成,
