### ISSUE TITLE
イベントlog 2020/04/19 雑学雑談 ~昆虫の話~

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#295]
担当：亀井, 中西
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)
[授業フォーマット](https://github.com/life-lab-kyoto/contents/wiki/%E6%8E%88%E6%A5%AD%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)
参加生徒：内藤結友, 桐村亮丞, 小湊和輝, 泉龍征

https://us02web.zoom.us/j/83154934368?pwd=UjhCd3Y1WVc3OGY2Ui8vYXF3NTFqUT09
Meeting ID: 831 5493 4368
Password: 054619

LIFE LAB公式LINEアカウント
https://lin.ee/7QEEWHp

[議事録 スライド](https://docs.google.com/presentation/d/1bIXFaymLDvZnYVTmEXwTIcBoSG02ETCf22DtFf4WvFg/edit#slide=id.p)

**Comment by kameiatsushi** [comment]
# 質問
- 内藤結友
ウデムシについて知りたい
アリがあんなに増えるのはなぜ
サバクトビバッタが日本にきたらどうなる

**Comment by NakanishiHiroki** [comment]
[危険生物.info](https://kikenseibutsu.info/)

**Comment by kameiatsushi** [comment]
# 話題
- 危険生物
- 昆虫食
