### ISSUE TITLE
イベントlog 2020/05/01 雑学雑談 ~googleの話~

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#319]
開催日時：5/1(金) 19:00~21:00
担当：亀井, 中西
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)
[授業フォーマット](https://github.com/life-lab-kyoto/contents/wiki/%E6%8E%88%E6%A5%AD%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)

Meeting ID: 851 3984 1983
Password: 013195

https://us02web.zoom.us/j/85139841983?pwd=YnJpNU1lam9yUlJsOXZ6cVlUSkF2QT09

YouTubeリンク：https://youtu.be/99Pvcj-vxb4

参加生徒：

**Comment by kameiatsushi** [comment]
# 話す内容
# 参加者管理

**Comment by NakanishiHiroki** [comment]
# MEMO
[sketch up](https://www.sketchup.com/plans-and-pricing-promo#for-personal)
