### ISSUE TITLE
イベントlog 2020/05/30 しんぶん読み解き講座

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#367]
授業担当：亀井, 中西
授業目的：新聞から思考を広げていく連想ゲームを体験をする
授業目標：テレワークの話から勉強する意義について考える
参考：#383
[授業用スライド](https://docs.google.com/presentation/d/1DcbL2A5sWulkPPjmScd2XGUyGJL9TPzPsjxQLOgrnLk/edit)
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)
[授業フォーマット](https://github.com/life-lab-kyoto/contents/wiki/%E6%8E%88%E6%A5%AD%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)

参加生徒：10人〜15人ぐらい
野田さん
中2男、小6女
野田さん姉
高2、中1、小5
谷口さん
中1男
有馬さん友人
小5男
小4女子

津賀さん
足立さん
下山さん（イベント会社）

# 事前課題
- 文章を読む
- わからない単語をリストアップして調べる
- 学校はリモート化すべきか（学校でリモート化できそうなものは何があるか考える）

**Comment by kameiatsushi** [comment]
# 記事
![20200522「原則テレワーク」出勤に戻る？_page-0001](https://user-images.githubusercontent.com/49800056/82890723-948ea880-9f87-11ea-8ac5-eb1f20b257b3.jpg)
# 要約
緊急事態宣言が全国的に解除されて、原則テレワークとしてきた企業の多くが出勤を認める方向である。ただ一度変わった働き方がこのまま残る可能性も出てきた。
新型コロナウイルスにより行われた働き方の変化が、従来の働き方を見直す機会となっている。パナソニックでは、テレワークが難しいとされてきた研究開発や営業部門でも活用され生産性が高まった部分もあるという。
従来はセキュリティー面の懸念などを理由にテレワークを試そうともしない企業が多かった。だが今回、多くの企業や社員がテレワークを体験し、メリットや課題を実感できた。今後効率的でゆとりある働き方を求める動きは広がるかもしれない。

**Comment by kameiatsushi** [comment]
# 授業の流れ
- 語彙の確認
- 内容の確認
- 議論
- まとめ

**Comment by kameiatsushi** [comment]
# 問い

**Comment by NakanishiHiroki** [comment]
多くの企業や社員がテレワークを体験し、メリットや課題を実感できた。
じゃあみんなに置き換えて考えてみよう。リモート授業はどうだった？
【問１】リモート授業のメリットやデメリットは？
なるほど。リモート授業にはこういったデメリットがあってこういうメリットもあることがわかったね。じゃあ、それを踏まえて
【問２】みんなはこれからリモート授業を受けたい？受けたくない？理由もつけて考えてみよう。~はリモートで~は学校で受けたいという意見でもOK。

**Comment by kameiatsushi** [comment]
# 振り返り
### 亀井
やはり、zoomに入れない問題があった
トラブル時にとりあえず見ておいてもらう用の動画があるのは助かる
事前にテスト通信会を設定した方がいいかもしれない
面談と称してやるのもアリかも
