### ISSUE TITLE
イベントlog 2020/06/14 しんぶん読み解き講座

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/contents#398]
授業担当：亀井, 中西
授業目的：新聞から思考を広げていく連想ゲームを体験をする
授業目標：
参考：#396
[授業用スライド](https://docs.google.com/presentation/d/1ydm9wk2YK8IIbMT2lL3KfzDYiDMextV6KhtflBragCg/edit?usp=sharing)
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)
[授業フォーマット](https://github.com/life-lab-kyoto/contents/wiki/%E6%8E%88%E6%A5%AD%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)

参加生徒：佐藤有恭, 野田幸太郎, 野田真子, すがのひとみ, 岩崎ここみ, 岩崎仁, 西山きら, 消しゴムさん, 山西結菜, 山西里菜

# 事前課題
- 出てきた単語に関しての豆知識を最低一つ用意する
例：テレワークのテレは離れたところという意味
　　パナソニックの創設者は松下幸之助　　など...
- 文章を読んでわからない単語や文章があればメモしておく

**Comment by NakanishiHiroki** [comment]
# 当日の流れ
## 授業前
## アイスブレイク
## 授業

**Comment by kameiatsushi** [comment]
# 問
### 模索
- 四字熟語、〇〇模索
暗中模索

### 昆虫
- クモ、ムカデは昆虫か？
ちがう

-  昆虫の例を挙げよ
カブトムシ、トンボ、カナブン、バッタ、カマキリ、テントウムシ、アリ、ハチなど

### タンパク質
- 人体における役割
身体をつくる

- では、身体をつくるとは何？
タンパク質は細胞のもとになる
身体はほぼ全て細胞からなる

- どんな食べ物に多く含まれる？
肉、卵、魚、大豆

### 昆虫食
- 昆虫食べたことある？ 食べたい？

- 昆虫食の例
イナゴの佃煮、ハチノコ、タガメ、アントシカダ（コオロギラーメン）

### 人口増加
- 他にどんな問題が起こる？
食糧不足、居住地不足、物価の高騰、エネルギー不足、ゴミの処理、水不足、働き口がなくなる、木の伐採が加速する

- それらにどう対処すればいい？
火星に移住する、新エネルギーの開発、地下に土地を開拓する、建物を高くする、貧富の差をなくす（でもどうやって？）

### 経済成長に伴って肉食が普及し
- なぜ肉食はお金がかかるのか？
穀物を大量に消費する
加工する必要がある
保存が効かない

### 牛肉1kgの生産に必要な穀物は8kg程度
- 700kgの肉牛に必要な穀物は？
5600kg

**Comment by kameiatsushi** [comment]
お菓子に蚕の糞が入ってるのに驚いた
石垣島のユーグレナのカフェに行った
