### ISSUE TITLE
イベントlog 2020/06/28 しんぶん読み解き講座

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/contents#414]
授業担当：亀井, 中西
授業目的：新聞から思考を広げていく連想ゲームを体験をする
授業目標：
参考：[ヒト臓器 動物でつくる](https://github.com/life-lab-kyoto/article/issues/1)
[授業用スライド](https://docs.google.com/presentation/d/1z0tkDzxzhRWPp2PnUIF7rfn7Lbpoq95_9_iAvCYWMmU/edit#slide=id.g81e9702c7c_0_89)
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)

参加生徒：野田真子, 野田幸太郎, 岩崎心美, 岩崎仁一郎, 西山きら

# 事前課題
【事前課題】

今回もかめちゃん＆ひろきより事前課題が出ています。

前回と違い、授業開始までにメールで送ってもらう形になります。

送信先アドレス：life.lab.20190401@gmail.com

⚠メールには自分の名前を書いておいてください！

 

【1】出てきた単語に関しての豆知識を最低一つ用意、授業開始までに上記アドレスにメールを送る。

★用意してもらった豆知識は出来るだけ発表してもらおうと思っています。

授業内で発表する時間を設ける為に、メール送信にご協力ください。

 

【2】文章を読んでわからない単語や文章があれば、授業開始までに上記アドレスにメールを送る。

★文章自体が難しいので途中までしか読めなかったり、一部しか読めなくても構いません。

授業の初めに内容を簡単に解説しますので安心してください。

**Comment by NakanishiHiroki** [comment]
# 授業の流れ
- 15:00~　講義内ルール説明
- 15:15~　内容理解
1.絶対に抑えるべき単語確認＆文章要約
2.みんなの豆知識発表
【キリの良いところで休憩5分　15:45くらい？】
- 16:15~　ふりかえり
- 16:25~　アンケート

**Comment by NakanishiHiroki** [comment]
西山きら
【1】「iPS細胞」「遺伝子」「胚」
【2】「膵島」「動物性集合胚」「規制法」「ヒトとネズミでは種の「距離」が遠い」「芽」「腎原基」「人工透析」「臨床研究」「拒絶反応」「抵抗感」

**Comment by kameiatsushi** [comment]
# 振り返り
## 事前MTG
イベントページをつくっている
そこに他の企画も入る
継続してやるのはLIFE LABのみ
今後、撮った動画はLIFE LABのアカウントでアップしていく

**Comment by NakanishiHiroki** [comment]
# チャット
14:53:23	 開始 ひろき : 全員集合～
15:00:18	 開始 ひろき : チャットに名前打って送って～
15:00:27	 開始 有恭 佐藤 : 佐藤　有恭
15:00:28	 開始 tomohiko noda : 野田真子
15:00:33	 開始 岩崎 勝 : ここみ
15:00:34	 開始 かめちゃん : 亀井敦史
15:00:39	 開始 Tomohiro Nishiyama : 西山　きら
15:00:40	 開始 岩崎 勝 : 仁一郎
15:00:43	 開始 tomohiko noda : 野田幸太郎
15:00:45	 開始 ひろき : なかにしひろき
15:02:01	 開始 ひろき : 中学生でも難しい文章でした
15:03:36	 開始 ひろき : ここに思ったこととか考えたこといっぱい書いていって！
15:03:50	 開始 ひろき : 疑問でも何でも！
15:07:10	 開始 有恭 佐藤 : 細胞
15:07:16	 開始 tomohiko noda : 細胞
15:07:29	 開始 岩崎 勝 : 細胞
15:07:43	 開始 Tomohiro Nishiyama : たくさんの細胞
15:08:49	 開始 ひろき : ヒトの細胞は昔60兆と言われていた
15:09:14	 開始 Tomohiro Nishiyama : っr
15:09:47	 開始 ひろき : 今は37兆と言われている。
15:10:48	 開始 ひろき : 卵子が一番大きな細胞
15:11:07	 開始 ひろき : 赤血球の20倍以上大きい
15:12:28	 開始 ひろき : ダチョウの卵も一つの細胞
15:13:36	 開始 ひろき : 発生(はっせい)と分化(ぶんか)
15:15:05	 開始 ひろき : 細胞は分裂して増えていく
15:15:36	 開始 ひろき : 基本的にコピーされるが途中から役割が決まっていく
15:16:57	 開始 ひろき : 分化する前の状態を胚
15:18:07	 開始 ひろき : 生物の種みたいな状態
15:18:34	 開始 ひろき : 親となんで顔似るん？
15:18:36	 開始 有恭 佐藤 : DNA
15:18:42	 開始 tomohiko noda : 遺伝子
15:18:44	 開始 Tomohiro Nishiyama : 遺伝子
15:19:53	 開始 岩崎 勝 : わからない
15:21:12	 開始 Tomohiro Nishiyama : 遺伝子の本体がDNA
15:23:05	 開始 ひろき : 遺伝子は生物の設計図
15:23:25	 開始 ひろき : DNAはデオキシリボ核酸
15:23:47	 開始 ひろき : ポケモンのデオキシスはそこから来てるよ
15:23:55	 開始 有恭 佐藤 : なんにでもなれる細胞
15:24:21	 開始 Tomohiro Nishiyama : どんな細胞にでもなれる
15:25:09	 開始 ひろき : 二人とも正解
15:26:42	 開始 ひろき : 分化した後の細胞を分化する前の状態に戻せたことが大発見
15:27:02	 開始 ひろき : iPhone
15:27:11	 開始 ひろき : アイポッド１
15:27:20	 開始 ひろき : iPod
15:27:41	 開始 Tomohiro Nishiyama : 知ってる
15:28:17	 開始 Tomohiro Nishiyama : お父さんが持ってる
15:29:32	 開始 ひろき : 幹細胞
15:30:02	 開始 ひろき : ES細胞も万能細胞
15:30:37	 開始 ひろき : 受精卵はもう人間？
15:31:25	 開始 ひろき : ES細胞は受精卵を基に作られた万能細胞
15:32:38	 開始 ひろき : DNAの情報がすべて同じ
15:32:44	 開始 ひろき : クローン
15:33:49	 開始 ひろき : 有性生殖をする生き物(人間もそう)は父と母の遺伝子を半分ずつもらっているのでクローンにならない
15:34:00	 開始 Tomohiro Nishiyama : 一卵性の双子との違いは？
15:36:50	 開始 ひろき : ありがとうございます！
15:40:04	 開始 ひろき : ジャガイモはクローン
15:42:52	 開始 ひろき : 一卵性双生児はクローンらしいです！
15:44:22	 開始 Tomohiro Nishiyama : 写真送れますか？
15:44:52	 開始 ひろき : 何の写真かな？
15:48:24	 開始 ひろき : ーーーーーーー
15:48:40	 開始 有恭 佐藤 : 英語圏においては、大きなネズミを「ラット」、小さなネズミを「マウス」と呼び分けることが多い
15:48:45	 開始 ひろき : ラット：大きいネズミ(ドブネズミとか)
15:48:58	 開始 ひろき : マウス：ハツカネズミとか
15:49:12	 開始 ひろき : 有恭ナイス
15:51:51	 開始 かめちゃん に ひろき(プライベート) : 写真きてるしスライドに貼ってくれる？
15:53:21	 開始 ひろき に かめちゃん(プライベート) : ok
15:53:26	 開始 ひろき に かめちゃん(プライベート) : 貼った
15:54:46	 開始 ひろき : ランゲルハンス島では血糖値を上げたり下げたりして調整している
15:55:35	 開始 ひろき : ーーーーーーーーーーー
15:55:47	 開始 ひろき : 酵素
15:55:52	 開始 ひろき : (こうそ)
15:57:31	 開始 ひろき : 遺伝子操作の方法はいくらかあるので気になったらまた調べてみてね
15:58:20	 開始 ひろき : ーーーーーーーーーーー
15:58:30	 開始 ひろき : 正直気持ち悪い実験
15:58:41	 開始 ひろき : ーーーーーーーーーー
16:00:15	 開始 ひろき : 質問あったらチャットに書いてや～
16:00:27	 開始 ひろき : ーーーーーーーーーーー

16:01:01	 開始 ひろき : 腎臓の役割
16:01:11	 開始 ひろき : ①尿を作る
16:01:28	 開始 ひろき : ②体の調子を整える
16:02:20	 開始 ひろき : ③血圧調整
16:02:36	 開始 ひろき : ④ホルモンを作る
16:03:38	 開始 ひろき : ーーーーーーーーーーー

16:04:00	 開始 ひろき : どうやって分化するかどうかの研究が進められていなかった
16:04:04	 開始 ひろき : ので
16:04:40	 開始 ひろき : クローン技術規制法で動物性集合胚を作ることが禁止されていた
16:04:56	 開始 ひろき : ーーーーーーーーーーー
16:06:09	 開始 ひろき : サル目とネズミ目が結構初めの段階で別れてるのがわかるよね
16:07:18	 開始 有恭 佐藤 : 技術革新
16:08:14	 開始 ひろき : ネズミは小さいからね
16:08:50	 開始 ひろき : 嫌な人挙手
16:11:25	 開始 ひろき : ーーーーーーーーーーー

16:11:47	 開始 ひろき : こっちの研究はヒトの体の中で臓器を育てる実験
16:12:40	 開始 ひろき : 糸球体で血液中の老廃物を尿に変える
16:13:18	 開始 ひろき : その尿からいるものを再び体に返すのが尿細管
16:13:39	 開始 ひろき : ーーーーーーーーーーー

16:13:43	 開始 ひろき : 豚河合荘
16:13:49	 開始 ひろき : 豚かわいそう
16:14:22	 開始 ひろき : サルの方が人間に近いからね
16:18:16	 開始 ひろき : ーーーーーーーーーーー

16:18:31	 開始 ひろき : 質問とかあったら書いて！
16:21:32	 開始 ひろき : ーーーーーーーーーーー

16:21:41	 開始 ひろき : ほないまから振り返り
