### ISSUE TITLE
ヒト臓器 動物でつくる 議論パート 案

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#429]
おもしろい問を羅列する
調査をする
# 参考
[NHK](https://www.nhk.or.jp/heart-net/life/index.html)

# やること
- 事前課題をまとめたスライドを用意する
- 議論をする上での心構えの作成
- 人体実験のガイドラインについて調べる
- 問に対するLIFE LABの解答を用意する

**Comment by kameiatsushi** [comment]
# 論点
- 動物実験で、人工的に繁殖させたマウスがありなら人工的につくったクローン人間もありなのでは？

## 動物実験のやってよい境界はどこ？
- 意識、痛覚、苦しみ
- 自然 or 養殖
- 絶滅危惧種はだめ
- 反射は思考か？
- 

## 人間はどこから人間？
- 胎児は人間じゃない
- 受精卵は5、6週目に脳内の電気的な活動が始まる
- 意識、痛覚
- キリスト教では受精卵の時点で人間の生命であると判断している

**Comment by kameiatsushi** [comment]
# 調査
## 死刑制度について
## 人権について
## 動物実験のガイドライン
## クローン調査

**Comment by kameiatsushi** [comment]
# 事前MTG 議事録（2020/07/03）

**Comment by kameiatsushi** [comment]
# 彩と議論
## 動物実験をやって良い境界はどこ
理想は動物実験を全くしないこと
薬の開発にどうしても必要

動物実験の例
マウスに電気ショックを与えて記憶力があるかどうかを実験する
墨を飲ませてどの臓器が分解するかを研究する

**Comment by kameiatsushi** [comment]
# 議論をする上での心構え
- 論の否定と人格の否定を区別する
- 話を最後まで聞く
- 理由もつける
- 言葉の定義をできるだけ明確にする
- 事実、意見、感想を区別する
- 目的によって議論の仕方が異なる
  - ブレストなら雑談みたいにどんどん飛躍させる
  - 課題解決ならそれに沿った議論を展開する
  - ディベート（討論）なら相手をいい負かすことが大事
- 議論は勝ち負けではない（ディベートという勝ち負けを競うものもある）
- くだらない主張は反論すらされない
- 議論は基本的に主張を否定することにより進めるものである

**Comment by NakanishiHiroki** [comment]
# 生物での実験境界線
## 中西
〇生物で実験をしてもいい境界

人間が脳を発達させ薬や治療法を開発する研究などが出来るようになったのは、キリンの首が長くなったのと同じで生存する可能性を上げるため手に入れた武器。(獲得しようと思ってしたわけではないだろうが。)
その武器は種として繁栄するためには使用しても問題は無い。つまり、動物実験はしても良い。
しかし、無駄な殺生はNG。無駄に殺生したところで人間が種として繁栄することはなさそう。

生物全般は個より種を繁栄させるために生きていると考えられそう。親が子を守ろうとするのは生物が若い未来あるものを守ろうとする本能っぽい。
よって、生物で実験する際は種の個体数がマイナスになってはならない。
繁殖させて使う分には良い。
食事で繁殖させていないものを捕って食べることがあるが、それは人間が本来置かれていた環境(狩りの環境)なので許される。

原則として生物は同種を殺してはいけないと考える。
人体実験をしてはいけないのは同種を殺すことになるから。
他の生物では共食いなどがあるが、あれは極限状態であるから許されるものと考える。
受精卵はアウト。

**Comment by kameiatsushi** [comment]
# 議論の心構え
論の否定と人格の否定を区別する
話を最後まで聞く
理由もつける
言葉の定義をできるだけ明確にする
事実、意見、感想を区別する
目的によって議論の仕方が異なる
ブレストなら雑談みたいにどんどん飛躍させる
課題解決ならそれに沿った議論を展開する
ディベート（討論）なら相手をいい負かすことが大事
議論は勝ち負けではない（ディベートという勝ち負けを競うものもある）
くだらない主張は反論すらされない
議論は基本的に主張を否定することにより進めるものである

**Comment by kameiatsushi** [comment]
# 授業の流れ
各自の事前課題をみていく

## 問：「かわいそうと思うかどうか」の判断基準を「動物実験してもよいか」に適用できるか
### 予想される解答
