### ISSUE TITLE
イベントlog 2020/07/18 知識の扉youtube

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/contents#446]
授業担当：亀井, 中西
授業目的：新聞から思考を広げていく連想ゲームを体験をする
授業目標：
参考：[ヒト臓器 動物でつくる](https://github.com/life-lab-kyoto/article/issues/1)
[授業用スライド](https://docs.google.com/presentation/d/1Q40xwxWPbqhpWleIRFhTfUPgUXVmwEAl3NhnAjgxzPc/edit?usp=sharing)

[zoom リンク](https://us02web.zoom.us/j/84318178268?pwd=MXdVQ3VlcHUzcXp3RTZUL2dhakNvQT09l)
Meeting ID: 843 1817 8268
Password: 657298

ストリームキー（エンコーダに貼り付け）
z30p-7uj2-5ycu-7240

ストリーム URL
rtmp://a.rtmp.youtube.com/live2

配信ページ
https://www.youtube.com/watch?v=K-je5T9f2t0&feature=youtu.be

**Comment by NakanishiHiroki** [comment]
# 授業の流れ
## ①講義の説明
どういう理念でどういう講義をしているか

## ②記事の内容説明
概要を前からざっとさらっていく

## ③議論
### 受精卵から胎児になり、出産という流れですが、どの時点で人間ですか？
### 意識ってそもそも何ですか？
### 医療で寿命を伸ばすべき？
### クローン人間はあり？
## ④
## ⑤
## ⑥
## ⑦

**Comment by NakanishiHiroki** [comment]
# 疑問リスト
- 人のiPS細胞入れただけでなぜネズミの膵臓が無くなったスペースにヒト細胞の膵臓ができるのか。
-

**Comment by kameiatsushi** [comment]
# 亀井 案
## 遺伝子操作ってどうやるの

## 人間と動物の境界
## 意識とは何か
## 善悪とは何か
## 膵臓について
- ランゲルハンス島の役割
- ホルモン
- ホメオスタシス

**Comment by kameiatsushi** [comment]
# 議事録
最初に全体の要約をざっとする

要約と次の話題を探すときにスクリーンシェアするぐらいで、他は2人の画面にする

ES細胞、iPS細胞についてしっかり解説する

**Comment by kameiatsushi** [comment]
# 振り返り
### 亀井
倫理ネタは永遠に話すことができるな
事前に話すネタを用意していたので、テンポもそこまで悪くならなかった
今後は倫理ネタ以外もやるので、その際はフリートークだけではしんどいかもしれないから、より準備が必要になるだろう

視聴者数が思ったほど伸びなかったのと、コメントも増えにくい
YouTubeやるときはもう少し告知をした方がいいかもしれないな
知り合いなのに、やってたことを知らないという人もいたし
