### ISSUE TITLE
イベントlog 2020/08/02 知識の扉

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#461]
授業担当：中西, 亀井
授業目的：新聞から思考を広げていく連想ゲームを体験をする
授業目標：
参考：
2020年3月2日
科学の扉
「音」で害虫だまし討ち　天敵を装い…減農薬へ新手法、「振動」も活用
https://digital.asahi.com/articles/DA3S14385709.html

https://zoom.us/j/93190817504
ミーティングID: 931 9081 7504
パスコード: 612750

[授業用スライド](https://docs.google.com/presentation/d/1vHApdRSNBtV4LwS6OeYfXhwzC-bxBO08PTNOiOXyv7Y/edit?usp=sharing)
[生徒管理シート](https://docs.google.com/spreadsheets/d/1bSnsjLZrEH-ryGokJPc-ABcNS4kBlCeSKDEygC4kjKA)
[LIFE LAB事典](https://docs.google.com/spreadsheets/d/1lywPMXLCYK4QYy_GlifTEN7zKjy2DH16S-GapJXaOYg)

参加生徒：野田幸太郎, 野田真子, 佐藤有恭, 長沢こと, 長沢みずき

# 要約
- 農薬ではなく音や振動で害虫をだまし討ちする手法が注目されている。
ブドウの伝染病を媒介するヨコバイは規則的な振動で求愛するが他のライバルのオスを邪魔するために不規則な振動も出す。繁殖の機会を減らすため、ブドウにその妨害振動を贈り続けた結果、実験を行ったぶどう園では三年程でヨコバイの数は半数になった。
- ほぼすべての昆虫は脚に振動を検知する感覚器を持っている。ガやウンカなどが超音波や葉の振動などで「会話」している。昆虫のこうした性質を逆手にとった、振動による防除の研究は２０１０年代に始まった。
マツノマダラカミキリは天敵のキツツキなどが歩くときの振動をまねて松の幹を揺らすと、産卵が減る。
トマトにつく害虫オンシツコナジラミやイチゴの害虫であるハスモンヨトウと呼ばれるガも振動で防除する研究がすすめられている。
- 環境に配慮した害虫防除は世界的な潮流で、農薬に限らずさまざまな手段を駆使して害虫を抑える「総合的有害生物管理」という考え方も提唱されている。振動や音を使う手法を農作業に組み込むには、コストの問題や作業手順をどうするのかなどの課題もあるが１０年ほどで普及するかもしれない。

**Comment by NakanishiHiroki** [comment]
# 授業の流れ
## ①アイスブレイク(自己紹介など)
時間がかかるので授業時間外に済ますのが良い。

## ②内容理解
### 要約
ざっくり本文の内容を要約してから単語の解説に入っていく
### 今回の記事を読む上で外せない知識
### 単語、豆知識解説
## ③
## ④
## ⑤
## ⑥

**Comment by kameiatsushi** [comment]
# 振り返り

# 振り返りMTG 議事録
カメラをオンにしてくださいというアナウンスを入れる

学生新聞社の協力は9月以降から
8／15(土) youtube

8/23の記事そろそろ決めないと
