### ISSUE TITLE
イベントlog 2020/08/15 知識の扉 YouTube版

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/contents#484]
授業担当：中西, 亀井
授業目的：新聞から思考を広げていく連想ゲームを体験をする
授業目標：
参考：
2020年3月2日
科学の扉
「音」で害虫だまし討ち　天敵を装い…減農薬へ新手法、「振動」も活用
https://digital.asahi.com/articles/DA3S14385709.html

スライド
https://docs.google.com/presentation/d/1vHApdRSNBtV4LwS6OeYfXhwzC-bxBO08PTNOiOXyv7Y

URL：https://us02web.zoom.us/j/89375769443
Meeting ID: 893 7576 9443
Passcode: 167464

[LIFE LAB事典](https://docs.google.com/spreadsheets/d/1lywPMXLCYK4QYy_GlifTEN7zKjy2DH16S-GapJXaOYg)

# 要約
- 農薬ではなく音や振動で害虫をだまし討ちする手法が注目されている。
ブドウの伝染病を媒介するヨコバイは規則的な振動で求愛するが他のライバルのオスを邪魔するために不規則な振動も出す。繁殖の機会を減らすため、ブドウにその妨害振動を贈り続けた結果、実験を行ったぶどう園では三年程でヨコバイの数は半数になった。
- ほぼすべての昆虫は脚に振動を検知する感覚器を持っている。ガやウンカなどが超音波や葉の振動などで「会話」している。昆虫のこうした性質を逆手にとった、振動による防除の研究は２０１０年代に始まった。
マツノマダラカミキリは天敵のキツツキなどが歩くときの振動をまねて松の幹を揺らすと、産卵が減る。
トマトにつく害虫オンシツコナジラミやイチゴの害虫であるハスモンヨトウと呼ばれるガも振動で防除する研究がすすめられている。
- 環境に配慮した害虫防除は世界的な潮流で、農薬に限らずさまざまな手段を駆使して害虫を抑える「総合的有害生物管理」という考え方も提唱されている。振動や音を使う手法を農作業に組み込むには、コストの問題や作業手順をどうするのかなどの課題もあるが１０年ほどで普及するかもしれない。

**Comment by kameiatsushi** [comment]
# トークテーマ
## 授業のおさらい
### 抵抗性を獲得する
### 音とは
### 真空
### ドップラー効果
### コウモリが

## その他
### コウモリは馬と近縁種
- レトロトランスポゾン
### ヘビとカエルが同じ遺伝子を持つことがある
### 耳の構造

**Comment by NakanishiHiroki** [comment]
https://digital.asahi.com/articles/ASN613SXLN55PLBJ002.html
